CREATE CONSTRAINT rated_key_unique IF NOT EXISTS FOR ()-[r:RATED]-() REQUIRE r.key IS UNIQUE;
CREATE CONSTRAINT watchlisted_key_unique IF NOT EXISTS FOR ()-[r:WATCHLISTED]-() REQUIRE r.key IS UNIQUE;
